apiVersion: v1
kind: Service
metadata:
  name: fe-law-ai-service
  namespace: production
  labels:
    app: fe-law-ai
spec:
  type: ClusterIP
  selector:
    app: fe-law-ai
  ports:
  - port: 80
    targetPort: 80