apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: production
  labels:
    app: be-law-ai
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: be-law-ai
  template:
    metadata:
      labels:
        app: be-law-ai
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: be-law-ai-container
        image: kunalmane/be-law-ai-project:v1.1
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: law-ai-secret
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi