apiVersion: v1
kind: Secret
metadata:
  name: law-ai-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.geminiApiKey | quote }}
  MONGO_URI: {{ .Values.mongoUri | quote }}

